[package]
name = "cdrs_helpers_derive"
version = "0.3.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]
description = "Derive CDRS helper traits"
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.1"
syn = "0.11.11"
quote = "0.3.15"
rand = "0.4.2"
